Fix timeout for http connections
gofractally/psibase pull request #560
Opened 2024-02-01 21:26 UTC by swatanabe

- The timer should be paused while processing transactions and queries
- Add an option to control the timeout

2024-02-04 17:26 UTC, James-Mart commented on doc/psidk/src/run-infrastructure/cli/psinode.md
> +  tells psinode how long to wait before closing an idle connection.
I think here would be the right place to mention that the units can be specified as: nothing (seconds), s, ms, us/μs, or ns

2024-02-04 17:26 UTC, James-Mart commented on programs/psinode/main.cpp
> +               "The maximum time for HTTP clients to send or receive a message");
I think something like "The timeout before the server closes idle HTTP connections" is a clearer description.

2024-02-04 17:26 UTC, James-Mart commented on programs/psinode/main.cpp
> +       "The maximum time for HTTP clients to send or receive a message");
I think something like "The timeout before the server closes idle HTTP connections" is a clearer description.

2024-02-04 17:33 UTC, James-Mart commented
I couldn't seem to force a timeout on boot even setting `http-timeout` to 1us

2024-02-05 14:16 UTC, swatanabe commented
> I couldn't seem to force a timeout on boot even setting `http-timeout` to 1us

Works for me:
```
$ ./psinode ./tmpdba -l 8080 --host psibase.127.0.0.1.sslip.io -p a --http-timeout=1us
$ rust/release/psibase boot -p a
Error: Failed to boot

Caused by:
    0: error sending request for url (http://psibase.127.0.0.1.sslip.io:8080/native/push_boot): connection error: Connection reset by peer (os error 104)
    1: connection error: Connection reset by peer (os error 104)
    2: Connection reset by peer (os error 104)
```

Note that 1ns won't work, because the representation of no timeout is currently wrong.

2024-02-05 15:03 UTC, James-Mart commented
```
$ psinode ./tempdb -l 8089 --host psibase.127.0.0.1.sslip.io -p a --http-timeout=1us
[2024-02-05T14:59:33.873Z] [warning]: unable to lock memory for ./tempdb. Try upgrading your shell's limits using "sudo prlimit --memlock=-1 --pid $$". If that doesn't work, try running psinode with "sudo".
[2024-02-05T14:59:33.874Z] [info]: Active producers: CFT:[]
[2024-02-05T14:59:33.875Z] [info]: Node is active producer
[2024-02-05T14:59:33.875Z] [info]: Starting block production for term 1 as a
[2024-02-05T14:59:33.875Z] [info]: Listening on 0.0.0.0:8089
[2024-02-05T14:59:33.975Z] [notice]: Need genesis block; use 'psibase boot' to boot chain
```
```
$ psibase -a http://psibase.127.0.0.1.sslip.io:8089/ boot -p a
███████████████████████████████████████████████████████████████████████ 10/10
Ok
```

2024-02-05 16:01 UTC, swatanabe commented
Can you check the value of the timeout in the config: `curl http://localhost:8089/native/admin/config | jq`? If you connect with the browser or another client that keeps persistent connections, does the timeout trigger?

2024-02-05 17:51 UTC, James-Mart commented
> Can you check the value of the timeout in the config

Interesting...  
```
psinode ./tempdb -l 8089 --host psibase.127.0.0.1.sslip.io -p a --http-timeout=1us
```

```
curl http://localhost:8089/native/admin/config | jq
...
"http_timeout": null,
...
```

2024-02-05 20:09 UTC, swatanabe commented on programs/psinode/main.cpp
> +      else if (s == "us" || s == "µs" || s == "μs")
U+00B5 (micro sign)
U+03BC (greek small letter mu)

I mostly included these for completeness. I don't expect anyone to actually type unicode in.

2024-02-05 20:12 UTC, James-Mart commented
> I see the problem. The value is being divided by 10, which causes it to truncate to 0, which was (before my last round of fixes) treated as infinite.

After your most recent fix, it's working. This is with 1us timeout:
```
$ psibase -a http://psibase.127.0.0.1.sslip.io:8089/ boot -p a
Error: Failed to boot

Caused by:
    0: error sending request for url (http://psibase.127.0.0.1.sslip.io:8089/native/push_boot): connection closed before message completed
    1: connection closed before message completed
```

2024-02-05 20:12 UTC, James-Mart approved these changes

2024-02-05 20:21 UTC, cool-ant commented on programs/psinode/main.cpp
> +      else if (s == "us" || s == "µs" || s == "μs")
Opt-m on a Mac. I do it cuz I can! :)

2024-02-05 20:26 UTC, swatanabe commented
> > I see the problem. The value is being divided by 10, which causes it to truncate to 0, which was (before my last round of fixes) treated as infinite.
> 
> After your most recent fix, it's working.

To see the current problem, set the timeout higher and then check the config: The timeout that it shows will be smaller than you specified.

2024-02-05 20:39 UTC, James-Mart requested changes
Unapproving for the following reason:


> @swatanabe: To see the current problem, set the timeout higher and then check the config: The timeout that it shows will be smaller than you specified.

2024-02-05 21:22 UTC, James-Mart commented
```
psinode ./tempdb -l 8089 --host psibase.127.0.0.1.sslip.io -p a --http-timeout=4s
```
```
$ curl http://localhost:8089/native/admin/config | jq
...
"http_timeout": "400000",
...
```

400`000 us = 0.4 sec

2024-02-05 22:16 UTC, swatanabe commented
> 400`000 us = 0.4 sec

I thought I fixed this in 594e43a

2024-02-06 14:02 UTC, James-Mart approved these changes

2024-02-06 14:25 UTC, merged