Change checkAuthSys signature to avoid passing the potentially large data, which is never actually used.
gofractally/psibase pull request #597
Opened 2024-02-20 18:35 UTC by swatanabe

This should increase the effective maximum action size, though it doesn't fully resolve it.

2024-02-20 18:47 UTC, James-Mart requested changes

2024-02-20 18:47 UTC, James-Mart commented on services/system/ProducerSys/include/services/system/ProducerSys.hpp
> +                        ServiceMethod               action,
Missing the corresponding reflection update

2024-02-20 18:47 UTC, James-Mart commented on services/system/TransactionSys/include/services/system/TransactionSys.hpp
Are you planning to provide a `getAction` action in case an auth service needs the data?

2024-02-20 18:54 UTC, swatanabe commented on services/system/TransactionSys/include/services/system/TransactionSys.hpp
I couldn't decide what to call it (the name `getAction` sounds like it should be behave like `psibase::getCurrentAction`), and I'm not sure that it will ever be needed, so I deferred it for now.

2024-02-21 00:50 UTC, James-Mart commented
Haha
```
/home/runner/work/psibase/psibase/libraries/psibase/native/tests/WatchdogTests.cpp:134: FAILED:
  CHECK( failed <= allowed_failures )
with expansion:
  6 <= 5
```

2024-02-21 13:56 UTC, James-Mart approved these changes

2024-02-21 14:23 UTC, merged