Add test service
gofractally/psibase pull request #689
Opened 2024-04-17 06:05 UTC by Velua

2024-04-17 13:53 UTC, James-Mart requested changes

2024-04-17 13:53 UTC, James-Mart commented on rust/psibase/src/services/demoapp1.rs
This should be deleted: we don't want `demoapp1` to show up in the `psibase::services` interface for everyone

2024-04-17 13:53 UTC, James-Mart commented on dev/DemoApp1/plugin/src/lib.rs
> +use psibase::services::demoapp1 as app_1;
demoapp1 should just be a separate service, not taken from psibase::services

2024-04-17 13:53 UTC, James-Mart commented on dev/DemoApp1/plugin/src/lib.rs
> +    fn multipli(a: u32, b: u32) -> String {
Why not `multiply`?

2024-04-17 13:53 UTC, James-Mart commented on dev/DemoApp1/plugin/src/lib.rs
>      fn helloworld2() -> Result<String, CommonTypes::Error> {
you could also delete helloworld and helloworld2 if you want, just to clean up the example app

2024-04-17 13:53 UTC, James-Mart commented on dev/DemoApp1/plugin/wit/world.wit
> +    multipli: func(a: u32, b: u32) -> string;
I think you should return `result<string, error>`. I expect almost every function in every plugin to return `result<something, error>`.

2024-04-17 13:53 UTC, James-Mart commented on dev/demoapp1-build-and-deploy.sh
At some point this should also be deleted. We can just set up demoapp1 in cmake so it's not deployed separately. Should also help make sure we don't break demoapp1 when its dependencies change (if we change common plugin interfaces, and such, for example).

2024-04-18 04:26 UTC, Velua commented on dev/demoapp1-build-and-deploy.sh
:+1:

2024-04-18 04:27 UTC, Velua commented
@James-Mart I've made those changes except the Rust wrapper import, I can't crack that... will try get on a call and sus it.

2024-04-23 13:35 UTC, James-Mart commented on dev/DemoApp1/plugin/wit/world.wit
> +    multiply: func(a: u32, b: u32) -> result<string, error>;
Bit odd for `multiply` to return a string

2024-04-30 15:46 UTC, James-Mart commented
Feel free to merge before you start getting merge conflicts

2024-04-30 20:05 UTC, merged