Improve package template
gofractally/psibase pull request #958
Opened 2024-12-12 16:10 UTC by James-Mart

* Adds prompts to template generation
  * psibase version
  * description
* Adds name validation
  * name doesn't contain numbers (it messes up the wit naming requirements) 
  * name <= 12 characters (makes it much more likely the account name will successfully roundtrip)
* Adds default tasks.json to generated app. If new app is opened as a new workspace in vscode, you will see UI buttons for "Build UI" and "Build package"
* Separates query service into separate service
* Adds query for historical event emission
* Add service unit test (in separate file)
* Adds a default readme for the generated app
* Add missing dependency on Sites package (caused boot to fail if package was used at boot)
* Generates app into a directory named "MyApp" (upper camel case) instead of "my-app" to match existing app naming conventions
* Uses split wit file convention (world.wit, impl.wit) to match existing wit conventions and make imports simpler

2024-12-17 21:18 UTC, cool-ant commented
This PR seems to replace/improve on the `package-templates` folder and should (I believe) remove that folder.

2024-12-17 21:41 UTC, swatanabe commented
> This PR seems to replace/improve on the `package-templates` folder and should (I believe) remove that folder.

I think it does, and github is getting confused for some reason. I see renames when I examine it in git.

2025-01-06 16:23 UTC, cool-ant approved these changes

2025-01-06 16:25 UTC, cool-ant requested changes
few more bits of feedback to address

2025-01-06 18:55 UTC, James-Mart commented on app-templates/basic-01/{{project-name | upper_camel_case}}/Cargo.toml.liquid
It's not a .toml file, it's a .liquid input file that results in a .toml file after generation. 
Practically, leaving .toml shows errors in the file over any the liquid syntax for IDEs that have toml syntax highlighting.

2025-01-06 19:04 UTC, James-Mart commented on package-templates/README.md
> +`cargo generate -p ./package-templates/ --destination ./services/user/ --init -v`
That use-case for cargo-generate is more applicable when creating templates for third-party devs who are pulling the template in from an external github repo. In our current case, this template is strictly for system devs in the context of our monorepo, so it might be confusing to show how to pull it in externally, only for it to fail if anyone tries to use it outside the monorepo.

2025-01-06 19:06 UTC, James-Mart commented on package-templates/README.md
> +`cargo generate -p ./package-templates/ --destination ./services/user/ --init -v`
Is there some use-case for pulling it in through github I'm not considering?

2025-01-06 19:08 UTC, James-Mart commented on app-templates/basic-01/{{project-name | upper_camel_case}}/Cargo.toml.liquid
If anything I think the .rs files that use liquid syntax should probably also be renamed to .liquid

2025-01-06 19:13 UTC, James-Mart commented on package-templates/basic-01/{{project-name | upper_camel_case}}/plugin/src/errors.rs
> +}
It's not an HTTP error though... do you mean show that it was a 200 response?

2025-01-08 18:08 UTC, cool-ant commented on package-templates/README.md
> +`cargo generate -p ./package-templates/ --destination ./services/user/ --init -v`
no, suppose not. I just knew it'll eventually be a use case and thought it'd be worth documenting while our minds are on it

2025-01-08 18:10 UTC, cool-ant commented on package-templates/basic-01/{{project-name | upper_camel_case}}/plugin/src/errors.rs
> +}
I suppose 200 would be one way to do it. I'm just thinking from the idea of demonstrating/instantiating stuff the right way and always having the option to delete what you don't need, having an example that included an http code would save going and reading macros (as I recently did) to figure out the proper syntax. Not a huge deal, but best would be a second error in a different situation that just shows how including an http return code would work

2025-01-08 18:11 UTC, cool-ant approved these changes

2025-01-08 18:42 UTC, James-Mart commented on package-templates/README.md
> +`cargo generate -p ./package-templates/ --destination ./services/user/ --init -v`
I see, I think we should leave that for the instructions when we build the template for external use

2025-01-08 18:45 UTC, merged